### ISSUE TITLE
There is a problem with the lock file lock in runner.

### ISSUE THREAD

**Issue by zong-zhe** [KusionStack/KCLVM#270]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

File lock only locks 'main'.

### 2. What did you expect to see? (Required)

File locks should lock all 'pkgpath'

### 3. What did you see instead (Required)

```
running 1 test
thread '<unnamed>' panicked at 'Compile KCL to LLVM error: "No such file or directory"', runner/src/assembler.rs:164:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
   3: core::result::Result<T,E>::expect
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1064:23
   4: <kclvm_runner::assembler::LlvmLibAssembler as kclvm_runner::assembler::LibAssembler>::assemble
             at ./src/assembler.rs:155:9
   5: <kclvm_runner::assembler::KclvmLibAssembler as kclvm_runner::assembler::LibAssembler>::assemble
             at ./src/assembler.rs:97:40
   6: kclvm_runner::assembler::KclvmAssembler::gen_libs::{{closure}}
             at ./src/assembler.rs:353:45
   7: <F as threadpool::FnBox>::call_box
             at /Users/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.8.1/src/lib.rs:95:9
   8: threadpool::spawn_in_pool::{{closure}}
             at /Users/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.8.1/src/lib.rs:769:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by zong-zhe** [comment]
File lock before refactoring: https://github.com/KusionStack/KCLVM/compare/main...Peefy:refine-llvm-assembler?expand=1

**Comment by zong-zhe** [comment]
Before PR: https://github.com/KusionStack/KCLVM/pull/71
Commit ID: 8d20c6a7e6f523e265c5210164fbfbdf641712cc

The file lock used in concurrent compilation will lock the file: 
```
// kclvm/src/lib.rs/kclvm_cli_run_unsafe
let file = if is_main_pkg {
    // Use temp main entry to prevent conflicts between different mains.

    // Compiling 'main.k' will lock a temporary file.
    PathBuf::from(&temp_entry_file)

} else {

    // Compiling other package files will lock the 'package_filepath.ll.lock'.lock.
    cache_dir.join(&pkgpath)

};
let ll_file = file.to_str().unwrap();
let ll_path = format!("{}.ll", ll_file);
let dylib_path = format!("{}{}", ll_file, Command::get_lib_suffix());
let mut ll_path_lock = fslock::LockFile::open(&format!("{}.lock", ll_path)).unwrap();
ll_path_lock.lock().unwrap();
```

**Comment by zong-zhe** [comment]
After PR: https://github.com/KusionStack/KCLVM/pull/215
Commit ID: 05def8dacc171b4e702d747d7ce261b10e747acc

The file lock used in concurrent compilation will lock the file:
```
// kclvm/runner/src/assembler.rs/impl KclvmAssembler/gen_libs
  let code_file = self.entry_file.clone();
  let code_file_path = assembler.add_code_file_suffix(&code_file);
  let lock_file_path = format!("{}.lock", code_file_path);
  let lib_path = format!("{}{}", code_file, Command::get_lib_suffix());
```

`self.entry_file` comes from the struct `KclvmAssembler`.
```
// kclvm/runner/src/assembler.rs/KclvmAssembler
pub(crate) struct KclvmAssembler {
    thread_count: usize,
    program: ast::Program,
    scope: ProgramScope,
    entry_file: String,
    single_file_assembler: KclvmLibAssembler,
}
```
`self.entry_file` is initialized at below:
```
// kclvm/runner/src/lib.rs
// Create a temp entry file and the temp dir will be delete automatically
let temp_dir = tempdir().unwrap();
let temp_dir_path = temp_dir.path().to_str().unwrap();
let temp_entry_file = temp_file(temp_dir_path);

// Generate libs
let lib_paths = assembler::KclvmAssembler::new(
    program,
    scope,
    temp_entry_file.clone(),
    KclvmLibAssembler::LLVM,
)
.gen_libs();
```

The method `temp_file()` will generate a file based on time and process_id.

**Comment by zong-zhe** [comment]
PR https://github.com/KusionStack/KCLVM/pull/272 fixed the bug, and created different file locks according to the current package type before concurrent compilation.

code from feca47083c7b5d6464c2b2b1f1a07ba5fe46c7e2:
```
// kclvm/runner/src/assembler.rs/impl KclvmAssembler/gen_libs

let entry_file = self.entry_file.clone();
let assembler = self.single_file_assembler.clone();
let is_main_pkg = pkgpath == kclvm_ast::MAIN_PKG;

// Created different file locks according to the current package type before concurrent compilation
let file = if is_main_pkg {
    PathBuf::from(entry_file) // Main package 
} else {
    cache_dir.join(&pkgpath) // Non-main package 
};
let code_file = file.to_str().unwrap().to_string();
... ...

// Concurrent compilation begin.
pool.execute(move || {
     ... ...
})
```

**Comment by zong-zhe** [comment]
> What is the solution to the problem? How can we be sure to prevent the issue from happening again?

I will add some more test cases for concurrent compilation to expose the problems as much as possible.
