### ISSUE TITLE
kusion compile failed when installed from brew (MacOS M1)

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/KCLVM#496]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. ```KusionStack/tap/kusion```
2. ```kusion compile -w <stack dir>```
3. error

### 2. What did you expect to see? (Required)

the compiled result

### 3. What did you see instead (Required)

```
✘  Generating Spec in the Stack ...
 ❌  Exception: Internal Error! Please report a bug to us: method=ExecProgram, err=Exception=Expecting value: line 1 column 1 (char 0), warn_json_result=rust libstd not found: Os { code: 2, kind: NotFound, message: "No such file or directory" }, stack trace=Traceback (most recent call last):
        File "/Users/amy/Library/Python/3.8/lib/python/site-packages/kclvm/program/exec/kclvm_cli.py", line 159, in kclvm_cli_native_run_dylib
          panic_info = json.loads(warn_json_result)
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
          return _default_decoder.decode(s)
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
          obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
          raise JSONDecodeError("Expecting value", s, err.value) from None
      json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/Users/amy/Library/Python/3.8/lib/python/site-packages/kclvm/internal/gpyrpc/protorpc.py", line 233, in _accept_one_call
          resp = service.call_method(method_name, req)
        File "/Users/amy/Library/Python/3.8/lib/python/site-packages/kclvm/internal/gpyrpc/gpyrpc_pb_protorpc.py", line 340, in call_method
          return self._instance.ExecProgram(req)
        File "/Users/amy/Library/Python/3.8/lib/python/site-packages/kclvm/program/rpc-server/__main__.py", line 172, in ExecProgram
          kcl_result = kclvm_exec.Run(
        File "/Users/amy/Library/Python/3.8/lib/python/site-packages/kclvm/program/exec/runner.py", line 129, in Run
          return kclvm_cli_native_run_dylib(args)
        File "/Users/amy/Library/Python/3.8/lib/python/site-packages/kclvm/program/exec/kclvm_cli.py", line 161, in kclvm_cli_native_run_dylib
          raise Exception(f"Exception={e}, warn_json_result={warn_json_result}")
      Exception: Exception=Expecting value: line 1 column 1 (char 0), warn_json_result=rust libstd not found: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

### 4. What is your KusionStack components version? (Required)
```
➜  kusion version
releaseVersion: v0.7.4
gitInfo:
    latestTag: v0.7.4
    commit: 6b0e343ee729a18d52cc480eb16f40447bdc53ea
    treeState: clean
buildInfo:
    goVersion: go1.18.10
    GOOS: linux
    GOARCH: amd64
    numCPU: 2
    compiler: gc
    buildTime: "2023-03-06 06:33:54"
dependency:
    kclvmgoVersion: v0.4.5
    kclPluginVersion: v0.4.4
```

**Comment by Peefy** [comment]
For KCLVM 0.4.5, U can use the command `sudo python3 -m pip install -U kclvm --user` to solve this issue. In KCLVM v0.4.6, we will completely remove Python and such issues will not occur.
